// client/src/components/Answer.vue
<template>
  <b-card
    :title="question.text"
    class="answer">
    <div slot="header">
      <router-link
        v-if="question.from"
        :to="question.from.username">{{ question.from.username }}</router-link>
      <span
        v-else
        class="text-muted">Anonymous</span>
      <time
        :title="moment.calendar()"
        class="text-muted">{{ moment.fromNow() }}</time>
    </div>
    <p class="card-text">{{ text }}</p>
    <hr>
    <b-button
      @click="like"
      :variant="isLiked ? 'outline-primary' : 'outline-secondary'"
      :disabled="!isAuthenticated">
      <i
        class="fa fa-heart"
        aria-hidden="true" /> Like {{ computedLikeCount ? computedLikeCount : '' }}</b-button>
    <a
      @click.prevent="openComments"
      href="#"
      class="card-link pull-right">Comments ({{ computedCommentCount }})</a>
    <div v-if="areCommentsOpen">
      <hr>
      <div v-if="comments.length">
        <comments :comments="comments"/>
        <br>
      </div>
      <form
        v-if="isAuthenticated"
        @submit.prevent="leaveComment">
        <b-form-group>
          <b-form-input
            type="text"
            v-model="comment"
            required
            placeholder="Leave a comment..." />
        </b-form-group>
        <b-button
          :disabled="!comment"
          type="submit">Comment</b-button>
      </form>
      <h5
        v-else
        class="text-center text-muted">You need to be authenticated to leave a comment</h5>
    </div>
  </b-card>
</template>

<script>
import moment from 'moment';
import Comments from './Comments.vue';
import { GET_COMMENTS, CREATE_COMMENT, LIKE_ANSWER, UNLIKE_ANSWER } from '../store/types';


export default {
  name: 'Answer',
  components: { Comments },
  props: {
    id: {
      type: Number,
      required: true,
    },
    text: {
      type: String,
      required: true,
    },
    timestamp: {
      type: Number,
      required: true,
    },
    question: {
      type: Object,
      required: true,
    },
    commentCount: {
      type: Number,
      required: true,
    },
    likeCount: {
      type: Number,
      required: true,
    },
  },
  data() {
    return {
      moment: this.getMoment(),
      areCommentsOpen: false,
      areCommentsLoading: true,
      likes: [],
      comments: [],
      comment: '',
    };
  },
  computed: {
    momentTick() {
      return this.$store.state.momentTick;
    },
    isAuthenticated() {
      return this.$store.state.isAuthenticated;
    },
    computedLikeCount() {
      if (this.likes) {
        return this.likes.length === 0 ? this.likeCount : this.likes.length;
      }

      return 0;
    },
    computedCommentCount() {
      return this.comments.length || this.commentCount;
    },
    user() {
      return this.$store.getters.getUser;
    },
    isLiked() {
      return this.likes && !!this.likes.filter(like => like.user_id === this.user.id).length;
    },
  },
  watch: {
    momentTick() {
      this.moment = this.getMoment();
    },
  },
  methods: {
    getMoment() {
      return moment.unix(this.timestamp);
    },
    async like() {
      if (this.isLiked) {
        const likes = await this.$store.dispatch(UNLIKE_ANSWER, this.id);
        this.likes = likes;
      } else {
        const likes = await this.$store.dispatch(LIKE_ANSWER, this.id);
        this.likes = likes;
      }
    },
    async openComments() {
      if (!this.comments.length && this.areCommentsLoading) {
        await this.getComments();
      }

      this.areCommentsOpen = !this.areCommentsOpen;
    },
    async getComments() {
      const comments = await this.$store.dispatch(GET_COMMENTS, this.id);
      this.comments = comments || [];
      this.areCommentsLoading = false;
    },
    async leaveComment() {
      const comment = await this.$store.dispatch(CREATE_COMMENT, {
        answerId: this.id,
        text: this.comment,
      });
      this.comments.push(comment);
      this.comment = '';
    },
  },
};
</script>

<style>
  .answer {
    margin-bottom: 20px;
  }
</style>

// client/src/components/profile/Answer.jsx
import React from 'react';
import { Link } from 'react-router';
import Moment from 'react-moment';
import moment from 'moment';
import { Panel, Button, FormGroup, FormControl } from 'react-bootstrap';
import Comments from './Comments';
import findIndex from 'lodash/findIndex';


export default class Answer extends React.Component {
  constructor(props) {
    const { id, likes, setAnswerLikes, setAnswerState, auth } = props;
    super(props);
    setAnswerLikes(id, likes && likes.length);

    if (auth.isAuthenticated && likes && findIndex(likes, { id: auth.user.id }) !== -1) {
      setAnswerState(id, {
        isLiked: true,
      });
    }
  }

  onChange(e) {
    this.props.setAnswerState(this.props.id, {
      [e.target.name]: e.target.value,
    });
  }

  async comment() {
    const { id, addAnswerComment, commentAnswer, state, setAnswerState } = this.props;
    const res = await commentAnswer(id, state.commentText);

    if (res.comment) {
      addAnswerComment(id, res.comment);
      setAnswerState(id, {
        commentText: '',
      });
    }
  }

  showComments() {
    this.props.setAnswerState(this.props.id, {
      isActiveComments: !this.props.state.isActiveComments,
    });
  }

  async like() {
    if (this.props.state.isLiked) {
      this.props.unlikeAnswer(this.props.id);
    } else {
      this.props.likeAnswer(this.props.id);
    }

    this.props.setAnswerState(this.props.id, {
      isLiked: !this.props.state.isLiked,
    });
  }

  render() {
    const { id, text, timestamp, question, from, comments, state, auth } = this.props;
    return (
      <Panel
        header={
          <div>
            { from ? <Link to={from}>{from}</Link> : <span>Anonymous</span> }
            <small title={moment(timestamp).calendar()} className="pull-right">
              <span className="text-muted"><Moment fromNow>{timestamp}</Moment></span>
            </small>
          </div>
        }
      >
        <h4>{question}</h4>
        <p>{text}</p>
        <hr />
        <Button
          bsSize="small"
          onClick={this.like.bind(this)}
          disabled={!auth.isAuthenticated}
          bsStyle={
            state.isLiked ? 'primary' : 'default'
          }
        >
          <i className="fa fa-heart" aria-hidden="true" /> Like {this.props.answersLikes[id] || ''}
        </Button>
        <Button bsStyle="link" onClick={this.showComments.bind(this)} className="pull-right">
          Comments ({(comments && comments.length) || 0})
        </Button>
        { state.isActiveComments &&
          <div>
            <hr />
            <Comments comments={comments} />
            { auth.isAuthenticated ?
              <div>
                <FormGroup>
                  <FormControl
                    name="commentText"
                    value={state.commentText}
                    componentClass="textarea"
                    placeholder="Leave a comment..."
                    onChange={this.onChange.bind(this)}
                  />
                </FormGroup>
                <FormGroup>
                  <Button onClick={this.comment.bind(this)} disabled={!state.commentText}>
                    Comment
                  </Button>
                </FormGroup>
              </div>
              :
              <center>
                <h3><small>You need to be authenticated to leave a comment</small></h3>
              </center>
            }
          </div>
        }
      </Panel>
    );
  }
}

Answer.defaultProps = {
  state: {
    isActiveComments: false,
    commentText: '',
    isLiked: false,
  },
};

Answer.propTypes = {
  id: React.PropTypes.number.isRequired,
  text: React.PropTypes.string.isRequired,
  timestamp: React.PropTypes.number.isRequired,
  question: React.PropTypes.string.isRequired,
  from: React.PropTypes.string,
  comments: React.PropTypes.array,
  likes: React.PropTypes.array,
  commentAnswer: React.PropTypes.func.isRequired,
  addAnswerComment: React.PropTypes.func.isRequired,
  state: React.PropTypes.object,
  setAnswerState: React.PropTypes.func.isRequired,
  auth: React.PropTypes.object.isRequired,
  answersLikes: React.PropTypes.object.isRequired,
  setAnswerLikes: React.PropTypes.func.isRequired,
  likeAnswer: React.PropTypes.func.isRequired,
  unlikeAnswer: React.PropTypes.func.isRequired,
};
