// src/components/Ask.vue
<template>
  <b-card
    v-if="!isAsked"
    class="ask">
    <form @submit.prevent="ask">
      <b-form-group label="Ask me whatever you want:">
        <b-form-input
          type="text"
          v-model="question"
          required
          placeholder="Enter a question..." />
      </b-form-group>
      <b-button
        variant="primary"
        :disabled="!question"
        type="submit">Ask</b-button>
      <b-form-checkbox
        class="mb-2 mr-sm-2 mb-sm-0"
        v-model="isAnon"
        v-if="isAuthenticated">Anonymously</b-form-checkbox>
    </form>
  </b-card>

  <b-card
    v-else
    border-variant="success"
    class="ask text-center">
    <span>
      Success! <strong>{{ profile.username }}</strong> has just received your question.
      <a
        @click.prevent="setNasked"
        href="#">Ask another question</a>
    </span>
  </b-card>
</template>

<script>
import { CREATE_QUESTION } from '../store/types';


export default {
  name: 'Ask',
  data() {
    return {
      isAnon: !this.isAuthenticated,
      isAsked: false,
      question: '',
    };
  },
  computed: {
    isAuthenticated() {
      return this.$store.state.isAuthenticated;
    },
    profile() {
      return this.$store.getters.getProfile;
    },
  },
  methods: {
    setNasked() {
      this.isAsked = !this.isAsked;
    },
    async ask() {
      await this.$store.dispatch(CREATE_QUESTION, {
        userId: this.profile.id,
        text: this.question,
        anon: this.isAnon,
      });
      this.question = '';
      this.setNasked();
    },
  },
};
</script>

<style>
  .ask {
    margin-bottom: 20px;
  }
</style>

// client/src/components/profile/Ask.jsx
import React from 'react';
import {
  Panel, FormGroup, FormControl,
  ControlLabel, Button, Checkbox, ButtonToolbar,
} from 'react-bootstrap';


export default class Ask extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      isAsked: false,
      isLoading: false,
      question: '',
      anonymously: false,
      status: 'default',
    };
  }

  onChange(e) {
    this.setState({
      [e.target.name]: e.target.value,
    });
  }

  setAnonymously() {
    this.setState({
      anonymously: !this.state.anonymously,
    });
  }

  setAsked() {
    this.setState({
      isAsked: !this.state.isAsked,
      status: 'default',
    });
  }

  async ask() {
    this.setState({
      isLoading: true,
      status: 'default',
    });

    try {
      const { userId, createQuestion } = this.props;
      const { question, anonymously } = this.state;
      await createQuestion(userId, question, { anonymously });

      this.setState({
        question: '',
        isLoading: false,
        isAsked: !this.state.isAsked,
      });
    } catch (e) {
      this.setState({
        status: 'danger',
        isLoading: false,
      });
    }
  }

  render() {
    const { isAuthenticated, username } = this.props;
    const { isAsked, isLoading, anonymously, question, status } = this.state;

    if (isAsked) {
      return (
        <Panel bsStyle="success">
          <center>
            <span>Success! <strong>{username}</strong> has just received your question.</span>
            &nbsp;
            <a onClick={this.setAsked.bind(this)}>Ask another question</a>
          </center>
        </Panel>
      );
    }

    return (
      <Panel bsStyle={status}>
        <FormGroup>
          <ControlLabel>Ask me whatever you want:</ControlLabel>
          <FormControl
            name="question"
            value={question}
            componentClass="textarea"
            placeholder="Ask a question..."
            onChange={this.onChange.bind(this)}
          />
        </FormGroup>
        <ButtonToolbar>
          <Button onClick={this.ask.bind(this)} disabled={!question || isLoading}>Ask</Button>
          {isAuthenticated && <Checkbox checked={anonymously} inline onChange={this.setAnonymously.bind(this)}>Ask anonymously</Checkbox>}
        </ButtonToolbar>
      </Panel>
    );
  }
}

Ask.propTypes = {
  userId: React.PropTypes.number.isRequired,
  isAuthenticated: React.PropTypes.bool.isRequired,
  username: React.PropTypes.string.isRequired,
  createQuestion: React.PropTypes.func.isRequired,
};
