// client/src/components/Comments.vue
<template>
  <b-list-group>
    <b-list-group-item
      v-for="comment in comments"
      :key="comment.id">
      <router-link :to="comment.user.username">{{ comment.user.username }}</router-link>
      {{ comment.text }}
    </b-list-group-item>
  </b-list-group>
</template>

<script>
export default {
  name: 'Comments',
  props: {
    comments: {
      type: Array,
      required: true,
    },
  },
};
</script>

// client/src/components/profile/Comments.jsx
import React from 'react';
import { ListGroup } from 'react-bootstrap';
import Comment from './Comment';


export default function Comments(props) {
  return (
    <ListGroup>
      {props.comments.map((comment) => {
        const { id, user, text, timestamp } = comment;
        return (<Comment
          id={id}
          username={user.username}
          text={text}
          timestamp={timestamp}
          key={id}
        />);
      })}
    </ListGroup>
  );
}

Comments.propTypes = {
  comments: React.PropTypes.array.isRequired,
};
