// client/src/components/Questions.vue
<template>
  <div class="col-xl-6">
    <span v-if="isLoading">Loading...</span>
    <div v-else-if="questionCount">
      <h4 v-if="questionCount == 1">There's a question especially for you:</h4>
      <h4 v-else>There are {{ questionCount }} questions especially for you:</h4>
      <hr>
    </div>
    <h3
      v-else
      class="text-muted text-center">You haven't received a single question yet</h3>
    <question
      v-for="question in questions"
      :key="question.id"
      :id="question.id"
      :text="question.text"
      :timestamp="question.timestamp"
      :from="question.from"
      :is-deleted="question.isDeleted" />
  </div>
</template>

<script>
import Question from './Question.vue';


export default {
  name: 'Questions',
  components: { Question },
  computed: {
    isLoading() {
      return this.$store.state.areQuestionsLoading;
    },
    isAuthenticated() {
      return this.$store.state.isAuthenticated;
    },
    questions() {
      return this.$store.getters.getQuestions;
    },
    questionCount() {
      return this.$store.getters.getQuestionCount;
    },
  },
  watch: {
    isAuthenticated() {
      this.$router.push('/');
    },
  },
};
</script>

// client/src/components/inbox/Questions.jsx
import React from 'react';
import { connect } from 'react-redux';
import Question from './Question';
import {
  incrementQuestionsCount, decrementQuestionsCount,
} from '../../actions/questionsCount';


function Questions(props) {
  const { questions, questionsCount } = this.props;

  return (
    <div>
      {questionsCount ?
        <div>
          {questionsCount === 1 ?
            <h3>There's a question especially for you:</h3>
            :
            <h3>There are {questionsCount} questions especially for you:</h3>
          }
          <hr />
          {questions.map(question => (
            <Question
              key={question.id}
              id={question.id}
              from={question.from ? question.from.username : null}
              text={question.text}
              timestamp={question.timestamp}
              decrementQuestionsCount={props.decrementQuestionsCount}
              incrementQuestionsCount={props.incrementQuestionsCount}
            />
          ))}
        </div>
        :
        <center>
          <h3 className="text-muted">You haven't received a single question yet.</h3>
        </center>
      }
    </div>
  );
}

Questions.propTypes = {
  questions: React.PropTypes.array.isRequired,
  questionsCount: React.PropTypes.number.isRequired,
  incrementQuestionsCount: React.PropTypes.func.isRequired,
  decrementQuestionsCount: React.PropTypes.func.isRequired,
};

function mapStateToProps(state) {
  return {
    questions: state.questions,
    questionsCount: state.questionsCount,
  };
}

export default connect(mapStateToProps, {
  incrementQuestionsCount, decrementQuestionsCount,
})(Questions);
