// client/src/components/profile/Answers.jsx
import React from 'react';
import Answer from './Answer';


export default function Answers(props) {
  const { answers, isMyProfile, username, isAuthenticated, addAnswerComment } = props;
  return (
    <div>
      { answers.length ?
        <div className="container-fluid">
          <h3>{ isMyProfile ? 'You have' : `${username} has`} {answers.length} answers:</h3>
          <hr />
          {answers.map((answer) => {
            const { id, text, question, comments, likes, timestamp } = answer;
            return (
              <Answer
                question={question.text}
                from={question.from && question.from.username}
                text={text}
                timestamp={timestamp}
                comments={comments}
                likes={likes}
                id={id}
                key={id}
                isAuthenticated={isAuthenticated}
                addAnswerComment={addAnswerComment}
              />
            );
          })}
        </div>
        :
        <center>
          <h3 className="text-muted">
            {isMyProfile ? 'You haven\'t' : `${username} hasn't`} answered a single question yet
          </h3>
        </center>
      }
    </div>
  );
}

Answers.propTypes = {
  answers: React.PropTypes.array.isRequired,
  isMyProfile: React.PropTypes.bool.isRequired,
  username: React.PropTypes.string.isRequired,
  isAuthenticated: React.PropTypes.bool.isRequired,
  addAnswerComment: React.PropTypes.func.isRequired,
};

// src/components/Answers.vue
<template>
  <div>
    <h3
      v-if="!hasProfileAnswers"
      class="text-muted text-center">
      {{ isMyProfile
        ? 'You haven\'t'
        : `${username} hasn't`
      }} answered a single question yet
    </h3>

    <answer
      v-for="answer in answers"
      :key="answer.id"
      :id="answer.id"
      :text="answer.text"
      :timestamp="answer.timestamp"
      :question="answer.question"
      :comment-count="answer.comment_count"
      :like-count="answer.like_count" />
  </div>
</template>

<script>
import Answer from './Answer.vue';


export default {
  name: 'Answers',
  components: { Answer },
  props: {
    isMyProfile: {
      type: Boolean,
      required: true,
    },
  },
  computed: {
    username() {
      return this.$store.getters.getProfile.username;
    },
    answers() {
      return this.$store.getters.getAnswers;
    },
    hasProfileAnswers() {
      return this.answers && this.answers.length;
    },
  },
};
</script>
